# Send a notification when the doorbell is pushed
  # - alias: 'Doorbell Notify'
  #   hide_entity: True
  #   trigger:
  #     platform: mqtt
  #     topic: Door_Status
  #     payload: 'Doorbell'
  #   action:
  #   - service: notify.notify
  #     data_template:
  #       message: "Someone is at the door."
  #     data:
  #       title: "Doorbell"
  #       data:
  #         file:
  #           url: "https://ha.danerich.co.uk/api/camera_proxy/camera.front_door?api_password=depenbech"


  # - alias: 'Plant light on before sun rise'
  #   hide_entity: True
  #   trigger:
  #     platform: sun
  #     event: sunrise
  #     offset: '-01:30:00'
  #   action:
  #     service: switch.turn_on
  #     entity_id: switch.plant_light
      
  # - alias: 'Light off sun rise'
  #   hide_entity: True
  #   trigger:
  #     platform: sun
  #     event: sunrise
  #     offset: '+00:00:00'
  #   action:
  #     service: switch.turn_off
  #     entity_id: switch.plant_light
      
  # - alias: 'Light on sun set'
  #   hide_entity: True
  #   trigger:
  #     platform: sun
  #     event: sunset
  #     offset: '+00:00:00'
  #   action:
  #     service: switch.turn_on
  #     entity_id: switch.plant_light
      
  # - alias: 'Light off after sun set'
  #   hide_entity: True
  #   trigger:
  #     platform: sun
  #     event: sunset
  #     offset: '+01:30:00'
  #   action:
  #     service: switch.turn_off
  #     entity_id: switch.plant_light
      
  - alias: 'Office light on when dark'
    hide_entity: True
    trigger:
      platform: numeric_state
      entity_id: sun.sun
      value_template: '{{ state.attributes.elevation }}'
      below: -2.5
    action:
      service: switch.turn_on
      entity_id: switch.office_light
  - alias: 'Office light off when 10:30'
    hide_entity: True
    trigger:
    - platform: time
      at: '22:30:00'
    action:
      service: switch.turn_off
      entity_id: switch.office_light
      
      
  - alias: 'LR Small lamp on when dark'
    hide_entity: True
    trigger:
      platform: numeric_state
      entity_id: sun.sun
      value_template: '{{ state.attributes.elevation }}'
      below: -1.0
    action:
      service: switch.turn_on
      entity_id: switch.living_room_small_lamp
  - alias: 'LR Bookcase lamp on when darker'
    hide_entity: True
    trigger:
      platform: numeric_state
      entity_id: sun.sun
      value_template: '{{ state.attributes.elevation }}'
      below: -1.5
    action:
      service: switch.turn_on
      entity_id: switch.hallway_lamp
  - alias: 'LR big lamp on when darkerer'
    hide_entity: True
    trigger:
      platform: numeric_state
      entity_id: sun.sun
      value_template: '{{ state.attributes.elevation }}'
      below: -2.5
    action:
      service: switch.turn_on
      entity_id: switch.living_room_big_lamp

      
      
  - alias: 'lights out when 10:30 if we are away'
    hide_entity: True
    trigger:
    - platform: time
      at: '22:35:00'
    condition:
    - condition: state
      entity_id: 'group.presence'
      state: 'not_home'
    action:
      - service: switch.turn_off
        entity_id: 
        - switch.hallway_lamp
        - switch.living_room_small_lamp
        - switch.living_room_big_lamp
      
      
  - alias: "Power state on HA start-up"
    hide_entity: True
    trigger:
      platform: homeassistant
      event: start
    action:
      - service: mqtt.publish
        data:
          topic: "cmnd/office_light/power1"
          payload: ""
      - service: mqtt.publish
        data:
          topic: "cmnd/lr_big_lamp/power1"
          payload: ""
      - service: mqtt.publish
        data:
          topic: "cmnd/lr_small_lamp/power1"
          payload: ""
      - service: mqtt.publish
        data:
          topic: "cmnd/lr_book_lamp/power1"
          payload: ""
          
  - alias: 'Start HomeKit'
    hide_entity: True
    trigger:
      - platform: homeassistant
        event: start
    action:
      - delay: 00:05
      - service: homekit.start
      
  # - alias: 'Big Lamp Toggle'
  #   initial_state: true
  #   trigger:
  #     - platform: mqtt
  #       topic: "tele/sonoffrf/RESULT"
  #   condition:
  #     condition: and
  #     conditions:
  #       - condition: template
  #         value_template: '{{ trigger.payload_json.RfReceived.Data == "004264" }}'
  #   action:
  #     service: switch.toggle
  #     entity_id: switch.living_room_big_lamp
      
  # - alias: 'Small Lamp Toggle'
  #   initial_state: true
  #   trigger:
  #     - platform: mqtt
  #       topic: "tele/sonoffrf/RESULT"
  #   condition:
  #     condition: and
  #     conditions:
  #       - condition: template
  #         value_template: '{{ trigger.payload_json.RfReceived.Data == "004261" }}'
  #   action:
  #     service: switch.toggle
  #     entity_id: switch.living_room_small_lamp
      
      
  - alias: 'Everything off on button press'
    initial_state: true
    trigger:
      - platform: mqtt
        topic: "tele/sonoffrf/RESULT"
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: '{{ trigger.payload_json.RfReceived.Data == "CC44B1" }}'
    action:
      - service: switch.turn_off
        entity_id: 
        - switch.hallway_lamp
        - switch.living_room_small_lamp
        - switch.living_room_big_lamp
        - switch.office_light
      - service: media_player.turn_off
        entity_id: media_player.sony_bravia_tv

#Bedside lamp switch's
  - alias: 'Dane bedside lamp toggle'
    initial_state: true
    trigger:
      - platform: mqtt
        topic: "tele/sonoffrf/RESULT"
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: '{{ trigger.payload_json.RfReceived.Data == "7923E1" }}'
    action:
      - service: switch.toggle
        entity_id: 
        - switch.danes_bedside_lamp

  - alias: 'Carl bedside lamp toggle'
    initial_state: true
    trigger:
      - platform: mqtt
        topic: "tele/sonoffrf/RESULT"
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: '{{ trigger.payload_json.RfReceived.Data == "ED08B1" }}'
    action:
      - service: switch.toggle
        entity_id: 
        - switch.carls_bedside_lamp

## Turn on bedside light if home and its dark out.
## weekday
## is 5:45am
## is dark out
## device_tracker.carl_rutters_iphone  device_tracker.dane_s_iphone
  - alias: 'Dane bedlight on in morning'
    hide_entity: True
    trigger:
      platform: time
      at: "05:45:00"
    condition:
      condition: and 
      conditions:
        - condition: numeric_state
          entity_id: sun.sun
          value_template: '{{ state.attributes.elevation }}'
          below: -2.5
        - condition: state
          entity_id: 'device_tracker.dane_s_iphone'
          state: 'home'
        - condition: time
          weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
    action:
      - service: switch.turn_on
        entity_id: 
        - switch.danes_bedside_lamp

  - alias: 'Carl bedlight on in morning'
    hide_entity: True
    trigger:
      platform: time
      at: "05:45:00"
    condition:
      condition: and 
      conditions:
        - condition: numeric_state
          entity_id: sun.sun
          value_template: '{{ state.attributes.elevation }}'
          below: -2.5
        - condition: state
          entity_id: 'device_tracker.carl_rutters_iphone'
          state: 'home'
        - condition: time
          weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
    action:
      - service: switch.turn_on
        entity_id: 
        - switch.carls_bedside_lamp

  - alias: 'Bedlights off in morning'
    hide_entity: True
    trigger:
      platform: numeric_state
      entity_id: sun.sun
      value_template: '{{ state.attributes.elevation }}'
      above: -2.5
    action:
      - service: switch.turn_off
        entity_id: 
        - switch.danes_bedside_lamp
        - switch.carls_bedside_lamp
    
        
## Charge Schedule to on the plug to charge when the electricity is cheaper
## on
  - alias: 'Charge schedule on'
    hide_entity: False
    initial_state: false
    trigger:
    - platform: time
      at: '01:30:00'
    action:
      service: switch.turn_on
      entity_id: 
      - switch.tplink_1
#off
  - alias: 'Charge schedule off'
    hide_entity: True
    trigger:
    - platform: time
      at: '03:30:00'
    action:
      - service: switch.turn_off
        entity_id: switch.tplink_1
      - service: automation.turn_off
        entity_id: automation.charge_schedule_on
## turn on the automation 
  - alias: 'Charge schedule trigger'
    initial_state: true
    trigger:
      - platform: mqtt
        topic: "tele/sonoffrf/RESULT"
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: '{{ trigger.payload_json.RfReceived.Data == "DDF8A1" }}'
    action:
      - service: automation.turn_on
        entity_id: automation.charge_schedule_on
      - service: tts.google_say
        entity_id: media_player.googlehome6320
        data:
          message: 'Charge schedule on'
     
     
#Nest turn on away mode when no presence
  - alias: 'Turn on eco mode when away'
    trigger:
      platform: state
      entity_id: group.presence
      to: 'not_home'
    action:
      - service: climate.set_preset_mode
        data:
          entity_id: climate.living_room
          preset_mode: 'Away and Eco'
          
#Nest turn on away mode off when we get home
  - alias: 'Turn off eco mode when home'
    trigger:
      platform: state
      entity_id: group.presence
      to: 'home'
    action:
      - service: climate.set_preset_mode
        data:
          entity_id: climate.living_room
          preset_mode: 'none'
          
#Nest turn off away mode to pre-heat
  - alias: 'Turn off eco mode to pre heat'
    trigger:
      platform: time
      at: "16:00:00"
    condition:
      condition: and
      conditions:
        - condition: numeric_state
          entity_id: 'weather.dark_sky'
          value_template: '{{ state.attributes.temperature }}'
          below: 9
    action:
      - service: climate.set_preset_mode
        data:
          entity_id: climate.living_room
          preset_mode: 'none'
      

#Doorbell
  - alias: 'Doorbell'
    initial_state: true
    trigger:
      - platform: mqtt
        topic: "tele/sonoffrf/RESULT"
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: '{{ trigger.payload_json.RfReceived.Data == "09B0B1" }}'
    action:
    - service: notify.ios_danes_iphone
      data:
        message: "Someone is at the front door"
        data:
          attachment:
            content-type: jpeg
          push:
            category: camera
          entity_id: camera.front_door
    - service: tts.google_say
      entity_id: media_player.googlehome6320
      data:
        message: 'Someone is at the front door'

!include xmas-automations.yaml
      