- alias: 'Start HomeKit'
  trigger:
    - platform: homeassistant
      event: start
  action:
    - delay: 00:05
    - service: homekit.start

## Charge Schedule to on the plug to charge when the electricity is cheaper
## on
- alias: 'Charge schedule on'
  initial_state: false
  trigger:
  - platform: time
    at: '01:30:00'
  action:
    service: switch.turn_on
    entity_id: 
    - switch.tplink_1
#off
- alias: 'Charge schedule off'
  trigger:
  - platform: time
    at: '03:30:00'
  action:
    - service: switch.turn_off
      entity_id: switch.tplink_1
    - service: automation.turn_off
      entity_id: automation.charge_schedule_on
## turn on the automation 
- alias: 'Charge schedule trigger'
  initial_state: true
  trigger:
    - platform: mqtt
      topic: "tele/sonoffrf/RESULT"
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: '{{ trigger.payload_json.RfReceived.Data == "09B0B1" }}'
  action:
    - service: automation.turn_on
      entity_id: automation.charge_schedule_on
    - service: tts.google_say
      entity_id: group.media_players
      data:
        message: 'Charge schedule on'
    
    
#Nest turn on away mode when no presence
- alias: 'Turn on eco mode when away'
  trigger:
    platform: state
    entity_id: group.presence
    to: 'not_home'
  action:
    - service: climate.set_preset_mode
      data:
        entity_id: climate.living_room
        preset_mode: 'Away and Eco'
        
#Nest turn on away mode off when we get home
- alias: 'Turn off eco mode when home'
  trigger:
    platform: state
    entity_id: group.presence
    to: 'home'
  action:
    - service: climate.set_preset_mode
      data:
        entity_id: climate.living_room
        preset_mode: 'none'
        
#Nest turn off away mode to pre-heat
- alias: 'Turn off eco mode to pre heat'
  trigger:
    platform: time
    at: "16:00:00"
  condition:
    condition: and
    conditions:
      - condition: numeric_state
        entity_id: 'weather.dark_sky'
        value_template: '{{ state.attributes.temperature }}'
        below: 9
  action:
    - service: climate.set_preset_mode
      data:
        entity_id: climate.living_room
        preset_mode: 'none'


## Doorbell Notification
## google home without sound
- alias: 'Doorbell Notification'
  trigger:
      - platform: mqtt
        topic: "tele/sonoffrf/RESULT"
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: '{{ trigger.payload_json.RfReceived.Data == "DDF8A1" }}'
  action:
  - service: notify.ios_danes_iphone
    data:
      message: "Someone is at the front door"
      data:
        attachment:
          content-type: jpeg
        push:
          category: camera
        entity_id: camera.front_door
  - service: notify.mobile_app_carl_rutters_iphone
    data:
      message: "Someone is at the front door"
      data:
        attachment:
          content-type: jpeg
        push:
          category: camera
        entity_id: camera.front_door
  - service: media_player.volume_set
    entity_id: media_player.googlehome7605
    data:
      volume_level: 0.0
  - service: media_player.turn_off
    entity_id: media_player.googlehome7605
  - service: media_player.turn_on
    entity_id: media_player.googlehome7605
  - delay:
        seconds: 1
  - service: media_player.volume_set
    entity_id: media_player.googlehome7605
    data:
      volume_level: 0.9
  - service: media_player.play_media
    entity_id: media_player.googlehome7605
    data:
      media_content_id: 'https://ha.danerich.co.uk/local/sounds/Jetsons-doorbell.mp3'
      media_content_type: music
  - delay:
        seconds: 6
  - service: media_player.volume_set
    entity_id: media_player.googlehome7605
    data:
      volume_level: 0.3
  - service: media_player.turn_off
    entity_id: media_player.googlehome7605


#Heating use to CSV file
#Date, Heating Time
- id: daily_heating_use
  alias: 'Daily Heating Use'
  trigger:
    platform: time
    at: '23:59:50'
  action:
  - service: notify.heating_log
    data_template:
      message: "{{ states('sensor.date')  }},{{ states('sensor.heating_time_on_today') }}"

#Backups
- alias: 'Run Snapshot Backup'
  trigger:
    platform: time
    at: "01:00:00"
  condition:
    condition: and 
    conditions:
      - condition: time
        weekday:
        - mon
  action:
    - service: script.create_snapshot
- alias: 'Run Dropbox Backup'
  trigger:
    platform: time
    at: "02:00:00"
  condition:
    condition: and 
    conditions:
      - condition: time
        weekday:
        - mon
  action:
    - service: hassio.addon_stdin
      data:
        addon: 7be23ff5_dropbox_sync
        input:
          command: upload
    - service: notify.mobile_app_dane_s_iphone
      data_template:
        title: 'Backup Dropbox'
        message: "The Dropbox 📦 backup has run."


# - alias: 'Apple Watch Glance'
#   trigger:
#   - minutes: /30
#     platform: time_pattern
#   action:
#     - service: shell_command.push_temp

#Bin Collection to Green
- alias: 'Change bin collection to green'
  trigger:
    platform: time
    at: "01:00:00"
  condition:
    condition: and 
    conditions:
      - condition: time
        weekday:
        - thu
      - condition: state
        entity_id: input_select.bin_collection_type
        state: 'Blue (General)'
  action:
    service: input_select.select_option
    data:
      entity_id: input_select.bin_collection_type
      option: "Green (Recycling)"

#Bin Collection to blue
- alias: 'Change bin collection to blue'
  trigger:
    platform: time
    at: "01:00:00"
  condition:
    condition: and 
    conditions:
      - condition: time
        weekday:
        - thu
      - condition: state
        entity_id: input_select.bin_collection_type
        state: 'Green (Recycling)'
  action:
    service: input_select.select_option
    data:
      entity_id: input_select.bin_collection_type
      option: "Blue (General)"


# Bin collection reminder
- alias: 'Green Bin Collection Reminder'
  trigger:
    platform: time
    at: "19:30:00"
  condition:
    condition: and 
    conditions:
      - condition: time
        weekday:
        - tue
      - condition: state
        entity_id: input_select.bin_collection_type
        state: 'Green (Recycling)'
  action:
    - service: notify.dane_and_carl
      data_template:
        title: '🟢 🗑 Green Bin Collection Tomorrow'
        message: "The recycling, garden waste and food waste will be picked up tomorrow."

- alias: 'Blue Bin Collection Reminder'
  trigger:
    platform: time
    at: "19:30:00"
  condition:
    condition: and 
    conditions:
      - condition: time
        weekday:
        - tue
      - condition: state
        entity_id: input_select.bin_collection_type
        state: 'Blue (General)'
  action:
    - service: notify.dane_and_carl
      data_template:
        title: '🔵 🗑 Blue Bin Collection Tomorrow'
        message: "The general waste, cans and food waste will be picked up tomorrow"

## Set Theme
- alias: 'Set theme at startup'
  trigger:
    platform: homeassistant
    event: start
  action:
    service: frontend.set_theme
    data:
      name: One Dark Theme
