- alias: 'Start HomeKit'
  trigger:
    - platform: homeassistant
      event: start
  action:
    - delay: 00:05
    - service: homekit.start

## Charge Schedule to on the plug to charge when the electricity is cheaper
## on
- alias: 'Charge schedule on'
  initial_state: false
  trigger:
  - platform: time
    at: '01:30:00'
  action:
    service: switch.turn_on
    entity_id: 
    - switch.tplink_1
#off
- alias: 'Charge schedule off'
  trigger:
  - platform: time
    at: '03:30:00'
  action:
    - service: switch.turn_off
      entity_id: switch.tplink_1
    - service: automation.turn_off
      entity_id: automation.charge_schedule_on
## turn on the automation 
- alias: 'Charge schedule trigger'
  initial_state: true
  trigger:
    - platform: mqtt
      topic: "tele/sonoffrf/RESULT"
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: '{{ trigger.payload_json.RfReceived.Data == "DDF8A1" }}'
  action:
    - service: automation.turn_on
      entity_id: automation.charge_schedule_on
    - service: tts.google_say
      entity_id: media_player.googlehome6320
      data:
        message: 'Charge schedule on'
    
    
#Nest turn on away mode when no presence
- alias: 'Turn on eco mode when away'
  trigger:
    platform: state
    entity_id: group.presence
    to: 'not_home'
  action:
    - service: climate.set_preset_mode
      data:
        entity_id: climate.living_room
        preset_mode: 'Away and Eco'
        
#Nest turn on away mode off when we get home
- alias: 'Turn off eco mode when home'
  trigger:
    platform: state
    entity_id: group.presence
    to: 'home'
  action:
    - service: climate.set_preset_mode
      data:
        entity_id: climate.living_room
        preset_mode: 'none'
        
#Nest turn off away mode to pre-heat
- alias: 'Turn off eco mode to pre heat'
  trigger:
    platform: time
    at: "16:00:00"
  condition:
    condition: and
    conditions:
      - condition: numeric_state
        entity_id: 'weather.dark_sky'
        value_template: '{{ state.attributes.temperature }}'
        below: 9
  action:
    - service: climate.set_preset_mode
      data:
        entity_id: climate.living_room
        preset_mode: 'none'

#Doorbell
- alias: 'Doorbell'
  initial_state: true
  trigger:
    - platform: mqtt
      topic: "tele/sonoffrf/RESULT"
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: '{{ trigger.payload_json.RfReceived.Data == "09B0B1" }}'
  action:
  - service: notify.ios_danes_iphone
    data:
      message: "Someone is at the front door"
      data:
        attachment:
          content-type: jpeg
        push:
          category: camera
        entity_id: camera.front_door
  - service: tts.google_say
    entity_id: media_player.googlehome6320
    data:
      message: 'Someone is at the front door'

#Power Meter ###      

#Power meter tariff switch
- alias: 'Tariff Switch Peak'
  trigger:
    - platform: time
      at: '07:30:00'
  action:
    - service: utility_meter.select_tariff
      data:
        entity_id: utility_meter.energy_daily
        tariff: day
- alias: 'Tariff Switch Offpeak'
  trigger:
    - platform: time
      at: '00:30:00'
  action:
    - service: utility_meter.select_tariff
      data:
        entity_id: utility_meter.energy_daily
        tariff: night

#Save daily energy use to CSV file
#Date, Energy Day, Energy Day Cost, Energy Night, Energy Night Cost, Energy Total Day, Energy Total Day Cost
- id: daily_energy_use_message
  alias: 'Daily Energy Use Message'
  trigger:
    platform: time
    at: '23:59:50'
  action:
  - service: notify.mobile_app_dane_s_iphone
    data_template:
      title: 'Energy Use âš¡ï¸'
      message: "Today's energy use was {{ states('sensor.total_energy') }} kWh. Costing Â£{{ states('sensor.energy_total_cost') }}"
  - service: notify.energy_log
    data_template:
      message: "{{ now() }},{{ states('sensor.energy_daily_day') }},{{ states('sensor.energy_day_cost') }},{{ states('sensor.energy_daily_night') }},{{ states('sensor.energy_night_cost') }},{{ states('sensor.total_energy') }},{{ states('sensor.energy_total_cost') }}"

#Backups
- alias: 'Run Snapshot Backup'
  trigger:
    platform: time
    at: "01:00:00"
  condition:
    condition: and 
    conditions:
      - condition: time
        weekday:
        - mon
  action:
    - service: hassio.snapshot_full
      data_template:
        name: >
          Backup_{{ now().strftime('%d-%m-%YT%H-%M-%S') }}
    - service: notify.mobile_app_dane_s_iphone
      data_template:
        title: 'Backup Snapshot'
        message: "The Snapshot ðŸ’¾ backup has run."

- alias: 'Run Dropbox Backup'
  trigger:
    platform: time
    at: "02:00:00"
  condition:
    condition: and 
    conditions:
      - condition: time
        weekday:
        - mon
  action:
    - service: hassio.addon_stdin
      data:
        addon: 7be23ff5_dropbox_sync
        input:
          command: upload
    - service: notify.mobile_app_dane_s_iphone
      data_template:
        title: 'Backup Dropbox'
        message: "The Dropbox ðŸ“¦ backup has run."