- alias: 'Office light on when dark'
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: -2.5
  action:
    service: switch.turn_on
    entity_id: switch.plug_s20_4_relay
- alias: 'Office light off when 10:30'
  trigger:
  - platform: time
    at: '22:30:00'
  action:
    service: switch.turn_off
    entity_id: switch.plug_s20_4_relay
    
    
- alias: 'Lights on when dark'
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: -1.0
  action:
    - service: switch.turn_on
      entity_id: 
      - switch.plug_s20_1_relay
    - service: light.turn_on
      data:
        entity_id: light.stairway_light
        brightness_pct: 30
        transition: 5
    - service: light.turn_on
      data:
        entity_id: light.track_lights
        brightness_pct: 20
        transition: 5

- alias: 'RGB light on when dark'
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: -1.0
  condition:
  - condition: state
    entity_id: 'group.presence'
    state: 'home'
  action:
    - service: light.turn_on
      data:
        entity_id: light.rgb_light
        rgb_color: [255, 218, 108]
        brightness: 255
        transition: 15

- alias: 'LR Bookcase lamp on when darker'
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: -1.5
  action:
    service: switch.turn_on
    entity_id: switch.plug_s20_3_relay

- alias: 'Lights on when darkerer'
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: -2.5
  action:
    - service: light.turn_on
      data:
          entity_id: light.big_lamp
          brightness_pct: 45
          transition: 5
    - service: light.turn_on
      data:
        entity_id: light.stairway_light
        brightness_pct: 45
        transition: 5

- alias: 'Garden Lights on when dark if home'
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: -2.5
  condition:
  - condition: state
    entity_id: 'group.presence'
    state: 'home'
  action:
    - service: switch.turn_on
      entity_id: 
      - switch.garden_lights

- alias: 'lights out when 10:30 if we are away'
  trigger:
  - platform: time
    at: '22:35:00'
  condition:
  - condition: state
    entity_id: 'group.presence'
    state: 'not_home'
  action:
    - service: light.turn_off
      entity_id: group.all_lights
    - service: switch.turn_off
      entity_id: group.all_lights
    
    
# - alias: "Power state on HA start-up"
#   trigger:
#     platform: homeassistant
#     event: start
#   action:
#     - service: mqtt.publish
#       data:
#         topic: "cmnd/office_light/power1"
#         payload: ""
#     - service: mqtt.publish
#       data:
#         topic: "cmnd/lr_big_lamp/power1"
#         payload: ""
#     - service: mqtt.publish
#       data:
#         topic: "cmnd/lr_small_lamp/power1"
#         payload: ""
#     - service: mqtt.publish
#       data:
#         topic: "cmnd/lr_book_lamp/power1"
#         payload: ""

# - alias: 'Everything off on button press'
#   initial_state: true
#   trigger:
#     - platform: mqtt
#       topic: "tele/sonoffrf/RESULT"
#   condition:
#     condition: and
#     conditions:
#       - condition: template
#         value_template: '{{ trigger.payload_json.RfReceived.Data == "CC44B1" }}'
#   action:
#     - service: switch.turn_off
#       entity_id: 
#       - switch.plug_s20_3_relay
#       - switch.plug_s20_1_relay
#       - switch.plug_s20_2_relay
#       - switch.plug_s20_4_relay
#     - service: light.turn_off
#       entity_id: 
#       - light.rgb_light
#     - service: media_player.turn_off
#       entity_id: media_player.sony_bravia_tv

#Bedside lamp switch's
# - alias: 'Dane bedside lamp toggle'
#   initial_state: true
#   trigger:
#     - platform: mqtt
#       topic: "tele/sonoffrf/RESULT"
#   condition:
#     condition: and
#     conditions:
#       - condition: template
#         value_template: '{{ trigger.payload_json.RfReceived.Data == "7923E1" }}'
#   action:
#     - service: switch.toggle
#       entity_id: 
#       - switch.plug_s26_1_relay

# - alias: 'Carl bedside lamp toggle'
#   initial_state: true
#   trigger:
#     - platform: mqtt
#       topic: "tele/sonoffrf/RESULT"
#   condition:
#     condition: and
#     conditions:
#       - condition: template
#         value_template: '{{ trigger.payload_json.RfReceived.Data == "ED08B1" }}'
#   action:
#     - service: switch.toggle
#       entity_id: 
#       - switch.plug_s26_2_relay

## Turn on lights if home and its dark out.
- alias: 'Lights on in morning if dark'
  trigger:
    platform: time
    at: "05:55:00"
  condition:
    condition: and 
    conditions:
      - condition: numeric_state
        entity_id: sun.sun
        value_template: '{{ state.attributes.elevation }}'
        below: -2.5
      - condition: state
        entity_id: 'group.presence'
        state: 'home'
      - condition: time
        weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    - service: switch.turn_on
      entity_id: 
      - switch.plug_s20_3_relay
      - switch.plug_s20_1_relay
    - service: light.turn_on
      data:
        entity_id: light.stairway_light
        brightness_pct: 45
        transition: 5
    - service: light.turn_on
      data:
        entity_id: light.rgb_light
        rgb_color: [255, 218, 108]
        brightness_pct: 100
        transition: 15

## Turn on bedside light if home and its dark out.
## weekday
## is 5:45am
## is dark out
## device_tracker.carl_rutters_iphone  device_tracker.dane_s_iphone
- alias: 'Dane bedlight on in morning'
  trigger:
    platform: time
    at: "05:45:00"
  condition:
    condition: and 
    conditions:
      - condition: numeric_state
        entity_id: sun.sun
        value_template: '{{ state.attributes.elevation }}'
        below: -2.5
      - condition: state
        entity_id: 'person.dane'
        state: 'home'
      - condition: time
        weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    - service: switch.turn_on
      entity_id: 
      - switch.plug_s26_1_relay

- alias: 'Carl bedlight on in morning'
  trigger:
    platform: time
    at: "05:45:00"
  condition:
    condition: and 
    conditions:
      - condition: numeric_state
        entity_id: sun.sun
        value_template: '{{ state.attributes.elevation }}'
        below: -2.5
      - condition: state
        entity_id: 'person.carl'
        state: 'home'
      - condition: time
        weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    - service: switch.turn_on
      entity_id: 
      - switch.plug_s26_2_relay

- alias: 'Lights off in morning when light'
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    above: -0.68
  action:
    - service: light.turn_off
      entity_id: group.all_lights
    - service: switch.turn_off
      entity_id: group.all_lights
      ## turn back on the under counter light
    - service: light.turn_on
      entity_id: group.under_counter_lights


#Lights out action
- alias: "Action Turn Lights Off"
  initial_state: true
  trigger:
    - platform: event
      event_type: ios.action_fired
      event_data:
        actionName: 'Lights Out'
  action:
    - service: light.turn_off
      entity_id: group.all_lights
    - service: switch.turn_off
      entity_id: group.all_lights
  

#Lights on action
- alias: "Action Turn Lights ON"
  initial_state: true
  trigger:
    - platform: event
      event_type: ios.action_fired
      event_data:
        actionName: 'Lights On'
  action:
    - service: light.turn_on
      entity_id: group.all_lights
    - service: switch.turn_on
      entity_id: group.all_lights


# turn off big lamp
# turn off tv
# turn off med light
# stairlight to 20%
# bedlights on
# delay 5 min
# turn off rgb light
# delay 10min
# turn off stairlight. 


#Bedtime Action
- alias: "Action Bedtime"
  initial_state: true
  trigger:
    - platform: event
      event_type: ios.action_fired
      event_data:
        actionName: 'Bedtime'
  action:
    - service: switch.turn_off
      entity_id: 
      - switch.plug_s20_2_relay #big lamp
      - switch.plug_s20_3_relay #med light
      - switch.plug_s20_4_relay #office
      - switch.plug_s20_1_relay #small lamp
    - service: switch.turn_on
      entity_id: 
      - switch.plug_s26_1_relay #bed lights
      - switch.plug_s26_2_relay
    - service: light.turn_on
      data:
        entity_id: light.rgb_light
        rgb_color: [255, 218, 108]
        brightness: 255
        transition: 1
    - service: light.turn_on
      data:
        entity_id: light.stairway_light
        brightness: 120
        transition: 15
    - delay: 0:05
    - service: light.turn_off
      data:
        entity_id: light.rgb_light
        transition: 15
    - service: light.turn_on
      data:
        entity_id: light.stairway_light
        brightness: 70
        transition: 15
    - delay: 0:05
    - service: light.turn_off
      data:
        entity_id: light.stairway_light
        transition: 15
