#### Power Meter ####

#Power meter tariff switch

## Summer 1:30 - 08:30
## Winter 00:30 - 07:30
## use UTC time so daylight saving will not effect this switch over

- alias: 'Tariff Switch Peak'
  trigger:
    - platform: template
      value_template: "{{ is_state('sensor.time_utc', '07:30') }}"
  action:
    - service: utility_meter.select_tariff
      data:
        entity_id: utility_meter.energy_daily
        tariff: day
    - service: utility_meter.select_tariff
      data:
        entity_id: utility_meter.energy_monthly
        tariff: day

- alias: 'Tariff Switch Offpeak'
  trigger:
    - platform: template
      value_template: "{{ is_state('sensor.time_utc', '00:30') }}"
  action:
    - service: utility_meter.select_tariff
      data:
        entity_id: utility_meter.energy_daily
        tariff: night
    - service: utility_meter.select_tariff
      data:
        entity_id: utility_meter.energy_monthly
        tariff: night

## Switch Electricity Cost
- alias: 'Electricity Cost Switch Day'
  trigger:
    - platform: template
      value_template: "{{ is_state('sensor.time_utc', '07:30') }}"
  action:
      service: input_number.set_value
      target:
        entity_id: input_number.electric_current_cost
      data:
        value: "{{ states('input_number.electric_day_cost') | float }}"

- alias: 'Electricity Cost Switch Night'
  trigger:
    - platform: template
      value_template: "{{ is_state('sensor.time_utc', '00:30') }}"
  action:
      service: input_number.set_value
      target:
        entity_id: input_number.electric_current_cost
      data:
        value: "{{ states('input_number.electric_night_cost') | float }}"

#Save daily energy use to CSV file
#Date, Energy Day, Energy Day Cost, Energy Night, Energy Night Cost, Energy Total Day, Energy Total Day Cost
- id: daily_energy_use_message
  alias: 'Daily Energy Use Message'
  trigger:
    platform: time
    at: '23:59:50'
  action:
  - service: notify.mobile_app_dane_s_iphone
    data_template:
      title: 'Energy Use ⚡️'
      message: "Today's energy use was {{ states('sensor.total_energy') }} kWh. Costing £{{ states('sensor.energy_total_cost') }}"
  - service: notify.energy_log
    data_template:
      message: "{{ states('sensor.date')  }},{{ states('sensor.energy_daily_day') }},{{ states('sensor.energy_day_cost') }},{{ states('sensor.energy_daily_night') }},{{ states('sensor.energy_night_cost') }},{{ states('sensor.total_energy') }},{{ states('sensor.energy_total_cost') }}"

## test power use sensor 
# - alias: 'Notify if power use sensor state unchanged'
#   trigger:
#     platform: template
#     value_template: "{% if is_state('sensor.power_use_last_update', '30 minutes') %}true{% endif %}"
#   action:
#     - service: notify.mobile_app_dane_s_iphone
#       data_template:
#         title: 'Power Usage Sensor Down'
#         message: "The power usage sensor was not updated for 30 minutes"